# Generated by Django 5.2.2 on 2025-06-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='User',
            new_name='user',
        ),
    ]
