# Generated by Django 5.2.2 on 2025-06-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_category_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='budgetlimit',
            unique_together={('category', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyspending',
            unique_together={('category', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='budgetlimit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlyspending',
            name='user',
        ),
    ]
